id: D1AD80E27
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:42:05+00:00'
last_modified: '2022-05-26T08:05:05.693314+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    ded0:
      image_group_id: I1PD95858
      title: མཆན་ཁུང་གི་སྦྱོར་བ།
      total_pages: 2043
      order: 13
      base_file: ded0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
