id: P7514778F
initial_creation_type: ocr
source_metadata:
  volumes:
    74601796ee41457893f2007ba3614f28:
      base_file: v013.txt
      image_group_id: I1PD95858
      title: མཆན་ཁུང་གི་སྦྱོར་བ།
      total_pages: 2043
      volume_number: 13
